### ISSUE TITLE
Re-export egui

### ISSUE THREAD

**Issue by IFcoltransG** [ryo33/egui_cable#6]
When I try to use the examples in my own code, I get an error that `Port` and similar types don't implement `Widget`. To use the `Widget` trait, I need to import it. I can't just import egui myself, because it has to be the same version egui_cable is using.
Unfortunately, egui isn't re-exported by egui_cable, so the `Widget` implementation is completely private. If egui_cable put `pub use egui;` in `lib.rs` that would solve the issue, because then I could import `Widget` from `egui_cable::egui` and have it be guaranteed to be the right version.

**Comment by ryo33** [comment]
Thanks 👍  I've released `0.4.0` with re-exporting `egui@0.20`. Have fun!
